import React from 'react'
import "./About.css"

export default function About(props) {
  return (
    <div className='About' style={{backgroundColor:(props.theme==="light")?"white":"#051833"}}>
      <h2 style={{color:(props.theme==="light")?"black":"white"}}>What Text Manager Is All About?</h2>
      <p  style={{color:(props.theme==="light")?"black":"white"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis hic voluptates a. Nostrum numquam iusto voluptatum dolore maiores non expedita eos est dolorem eius repellat quasi voluptates nobis, aspernatur esse quidem voluptate dolorum. Labore dolorum odio necessitatibus fuga corrupti hic, nostrum non. Maxime velit eos dolore et quaerat consequuntur repudiandae consectetur, a ut. Quis quos neque enim, sint magnam ex amet illum. Ea enim nisi illum excepturi consectetur accusantium, facilis alias molestias assumenda commodi asperiores omnis esse temporibus aut in blanditiis reprehenderit distinctio adipisci incidunt! Blanditiis quaerat temporibus excepturi sed libero veritatis magni iste, voluptate, tempore ratione, cupiditate saepe esse rem neque aut hic nulla quisquam amet accusantium. Temporibus dolorem harum, iusto aperiam ullam debitis soluta nam sapiente eos minima facilis perferendis molestias officia odit excepturi quam! Vel ad quaerat ipsam quisquam delectus, in fuga quibusdam sequi officiis expedita magnam enim unde, earum animi quidem aliquam modi praesentium voluptates reiciendis accusantium asperiores. Illum incidunt doloribus totam obcaecati sequi? Atque totam culpa libero? Atque quam porro quas, saepe error vitae ex provident fugit incidunt doloremque deserunt pariatur laborum nihil sint rerum animi omnis rem praesentium voluptates velit ab eos, recusandae aspernatur voluptatum! Sed, esse ut. Voluptatibus hic quos maiores non nam autem eveniet eaque deserunt delectus eum beatae corrupti alias quae laborum repellendus, minima voluptatem harum vel architecto, fugiat, iusto nobis excepturi obcaecati. Adipisci quidem placeat ducimus minus. Quaerat omnis quibusdam velit placeat nam. Incidunt quis beatae et totam quod delectus alias ducimus neque iusto nihil? Veniam natus eligendi doloribus dolorem laudantium porro, consectetur excepturi corrupti, tempore iste quo fugit corporis quas commodi dolores exercitationem non eveniet explicabo. Ipsum labore nostrum sapiente sit exercitationem deleniti molestias quas? Eveniet, repudiandae tempora, incidunt soluta nemo id quas odit molestias, corrupti dolorem porro. Accusantium odio nobis culpa, quia amet natus illum doloribus quam vel.</p>
    </div>
  )
}
